// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPIProject.Models;

namespace WeatherAPIProject.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20210521163241_WeatherMig")]
    partial class WeatherMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherAPIProject.Models.weather", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForeCast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowTemp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("City");

                    b.ToTable("w");
                });
#pragma warning restore 612, 618
        }
    }
}
